### PR TITLE
Pin node version in package.json

### PR DESCRIPTION
**Pull request by tim-schilling**
This prevents a person from running manage.py tailwind install and updating the dependencies for a different version of node than Azure can support.

### CODE REVIEW

**Comment by sarahboyce** [comment]
https://github.com/djangonaut-space/wagtail-indymeet/issues/226
Can we upgrade nodejs instead? :)

**Comment by tim-schilling** [comment]
Go for it!

**Review by sabderemane — APPROVED** [review]
I feel like this have been in another PR no?

**Comment by tim-schilling** [comment]
I'm moving forward with this as a pre-cursor to attempting to get our build to be compatible with a recent version of node.

**Pull request merged**
