### PR TITLE
Don't update wagtail reference index for survey responses

### PR DESCRIPTION
**Pull request by tim-schilling**
Follow-up to #349

### CODE REVIEW

**Review by sarahboyce — APPROVED** [review]
whaaaaaaat 🤯 
This is great ⭐ 
Maybe we need this for some of the account models also? (maybe profile)

**Comment by tim-schilling** [comment]
We may need to find a better way to do this in our app. I'm also not sure how it all works, but this is one option available to us.

**Comment by sarahboyce** [comment]
I think this problem goes away when we upgrade to wagtail 5+
https://docs.wagtail.org/en/v5.1.3/advanced_topics/reference_index.html

**Comment by tim-schilling** [comment]
Good find.

**Comment by tim-schilling** [comment]
Solved in #360

**Comment by tim-schilling** [comment]
@sarahboyce just read the docs link. I'm not sure I agree. Can you highlight the part that says that this is solved?

**Comment by sarahboyce** [comment]
"When introduced in Wagtail 4.1, the Reference Index recorded references in all application models by default. Wagtail 5.0 reduced the scope of the default models to those specifically linked with Wagtail."
https://docs.wagtail.org/en/v5.1.3/advanced_topics/reference_index.html#configuration

**Comment by tim-schilling** [comment]
Thank you. I'll need to rerun this test without the ignore prop to confirm then.

**Pull request closed without merging**
