### PR TITLE
Feat: sticky footer

### PR DESCRIPTION
**Pull request by raffaellasuardini**
Updated the footer to be a sticky one as requested 

* #388

### CODE REVIEW

**Comment by tim-schilling** [comment]
Could you add a screen shot of it on a page where you're partially scrolled down?

**Comment by tim-schilling** [comment]
I've got no problems with the approach. Just want to see it work before merging.

**Comment by raffaellasuardini** [comment]
Ok, let me know if this is what you're asking for.
The event page is the longest
Screenshot 2024-08-02 alle 17 41 10
The login page is the one with the smallest content
Screenshot 2024-08-02 alle 17 42 56

**Review by tim-schilling — APPROVED** [review]
:heavy_check_mark: :rocket: :clap:

**Pull request merged**
