### PR TITLE
add email confirmation workflow

### LINKED ISSUE #26: Create an auto email for sign up confirmations and other event
- Research what is the best option: Mandrill something? Postmark something?
-

### LINKED ISSUE #68: Add opt-in for email on user registration

### PR DESCRIPTION
**Pull request by RachellCalhoun**
closes #26
closes #68  
closes https://github.com/djangonaut-space/wagtail-indymeet/issues/74

### CODE REVIEW

**Comment by RachellCalhoun** [comment]
We still need to setup the email service and plug in the keys, but I was hoping to do that this week.

**Comment by RachellCalhoun** [comment]
@dawnwages  we need to set up mailgun (I think that's what we decided?) account but please ping me when you get here because I have some things to discuss with you.

**Comment by RachellCalhoun** [comment]
Do not merge for now, until we can test out mailgun keys

**Comment by RachellCalhoun** [comment]
the set up is working but sendgrid needs to verify the account..."under review" so I guess we wait. 
image

**Comment by RachellCalhoun** [comment]
going to try with mailjet, this is blocked until can verify the account and that it's working.

**Comment by RachellCalhoun** [comment]
Successfully sent mail with mailjet.

**Review by tim-schilling — APPROVED** [review]

**Pull request merged**
