### PR TITLE
Remove an unused !important that causes an error

### PR DESCRIPTION
**Pull request by MHLut**
Fixes https://github.com/djangonaut-space/wagtail-indymeet/issues/338.

### CODE REVIEW

**Comment by MHLut** [comment]
The failing pre-commit CI issues are not related to this change. See also https://github.com/djangonaut-space/wagtail-indymeet/issues/339.

**Review by sarahboyce — APPROVED** [review]

**Comment by MHLut** [comment]
Regarding the pre-commit autofixes, see https://github.com/djangonaut-space/wagtail-indymeet/pull/343

**Comment by MHLut** [comment]
@tim-schilling Heads-up

**Comment by MHLut** [comment]
Merged per Sarah's previous approval.

**Pull request merged**
