### PR TITLE
Standardize the blocks we are using across blog and general pages

### PR DESCRIPTION
**Pull request by RachellCalhoun**
related to #263

### CODE REVIEW

**Review by tim-schilling — COMMENTED** [review]
Love this. Thank you

**Comment by tim-schilling** [comment]
Do we need to delete any existing content before deploying this?

**Comment by RachellCalhoun** [comment]
@tim-schilling 
> Do we need to delete any existing content before deploying this?

None in prod, I copied the content then deleted two general pages in staging. So we should be good to go.

**Comment by tim-schilling** [comment]
Cool, let's merge this then deploy to production with the other style change.

**Pull request merged**
